apiVersion: appstudio.redhat.com/v1beta1
kind: RemoteSecret
metadata:
  name: registry-redhat-io-quay-token-secret-remote-secret
  namespace: managed-release-team-tenant
spec:
  secret:
    linkedTo:
    - serviceAccount:
        reference:
          name: rh-push-to-registry-redhat-io-sa
    - serviceAccount:
        reference:
          name: release-e2e-sa
    name: quay-token-secret
    type: kubernetes.io/dockerconfigjson
  targets:
  - namespace: managed-release-team-tenant
